-- Add registration_requests table and can_complete_profile to users

ALTER TABLE users ADD COLUMN can_complete_profile BOOLEAN DEFAULT FALSE;

CREATE TABLE registration_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  ig_profile VARCHAR(255),
  password_hash VARCHAR(255) NOT NULL,
  role_requested VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMP,
  processed_by VARCHAR(100),
  processed_at TIMESTAMP,
  notes VARCHAR(1000)
);

