-- Create planner table and portfolio_file table

CREATE TABLE planner (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  full_name VARCHAR(255),
  company_name VARCHAR(255),
  description TEXT,
  website VARCHAR(255),
  phone_number VARCHAR(64),
  email VARCHAR(255)
);

CREATE TABLE portfolio_file (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  file_path VARCHAR(1024),
  file_type VARCHAR(255)
);

